name: QMK Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          # Replace 'dasbob' and 'default' with your specific keyboard and keymap names
          qmk compile -kb dasbob -km default

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.hex
            *.bin
            *.uf2
